In [1]:
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

Matplotlib is building the font cache; this may take a moment.


We have 10 smaples, each constisting of 2 features. (i.e., $\vec{x}=(x_1,x_2)$)

$$X=\begin{bmatrix}
- & \vec{x}_{1} & - \\
 & \vdots  &  \\
- & \vec{x}_{10} & - \\
\end{bmatrix}$$

In [18]:
X= np.array(
[[ 0.11,0.05],
 [ 1.76,0.21],
 [ 1.59,1.56],
 [ 0.07,-0.23],
 [ 1.01,-1.32],
 [-0.06,-0.78],
 [ 1.92,1.52],
 [-0.83,-1.61],
 [-0.52,0.44],
 [ 0.57,0.76]])

In [19]:
print(X) # input X

[[ 0.11  0.05]
 [ 1.76  0.21]
 [ 1.59  1.56]
 [ 0.07 -0.23]
 [ 1.01 -1.32]
 [-0.06 -0.78]
 [ 1.92  1.52]
 [-0.83 -1.61]
 [-0.52  0.44]
 [ 0.57  0.76]]


$\vec{y}=w_1x_1+w_2x_2+b,$

where $w_1=1, w_2=-2$, and $b=3$.

In [20]:
true_w1, true_w2, true_b = 1, -2, 3
y = true_w1*X[:,0] + true_w2*X[:,1] + true_b

In [21]:
print(y)

[3.01 4.34 1.47 3.53 6.65 4.5  1.88 5.39 1.6  2.05]


Add noise to y and reshape it into a column vector:

In [22]:
e = np.random.randn(10)*0.1
y= y + e

y = y.reshape(-1,1)
print(y) ## True y values

[[2.98640238]
 [4.37188555]
 [1.43441169]
 [3.41334039]
 [6.64188876]
 [4.62337772]
 [1.82264062]
 [5.377855  ]
 [1.70205578]
 [1.97594418]]


$$\tilde{X}=\begin{bmatrix}
- & \vec{x}_{1} & - & 1 \\
 & \vdots  & & \vdots \\
- & \vec{x}_{10} & - & 1 \\
\end{bmatrix}=[X, \vec{1}]$$

In [23]:
ones = np.ones((X.shape[0],1))
print(ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [24]:
X_tilde = np.concatenate([X,ones], axis=1)
print(X_tilde)

[[ 0.11  0.05  1.  ]
 [ 1.76  0.21  1.  ]
 [ 1.59  1.56  1.  ]
 [ 0.07 -0.23  1.  ]
 [ 1.01 -1.32  1.  ]
 [-0.06 -0.78  1.  ]
 [ 1.92  1.52  1.  ]
 [-0.83 -1.61  1.  ]
 [-0.52  0.44  1.  ]
 [ 0.57  0.76  1.  ]]


Calculate

$\tilde{w}=\begin{bmatrix} w_1 \\ w_2 \\ b \end{bmatrix}=(\tilde{X}^T\tilde{X})^{-1}\tilde{X}^T\vec{y}$

In [25]:
(X_tilde.T)@X_tilde # @: matrix multiplication (cf: *:Hadamard)

array([[11.637 ,  6.0121,  5.62  ],
       [ 6.0121, 10.5576,  0.6   ],
       [ 5.62  ,  0.6   , 10.    ]])

In [26]:
np.linalg.inv(((X_tilde.T)@X_tilde))

array([[ 0.18457805, -0.09955349, -0.09775966],
       [-0.09955349,  0.14873746,  0.04702481],
       [-0.09775966,  0.04702481,  0.15211944]])

In [27]:
np.round((((X_tilde.T)@X_tilde) @ np.linalg.inv(((X_tilde.T)@X_tilde))),1) ## cross check

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [28]:
w_tilde = np.linalg.inv(((X_tilde.T)@X_tilde))@X_tilde.T@y
print(w_tilde)

[[ 0.98454476]
 [-2.00910409]
 [ 3.0022123 ]]


In [29]:
w = w_tilde[:-1].reshape(-1)
b = w_tilde[-1]

In [30]:
print(w)
print(b)

[ 0.98454476 -2.00910409]
[3.0022123]


In [31]:
y_hat = X@w.T + b ## or X_tilde@w_tilde

In [32]:
y_hat

array([3.01005702, 4.31309921, 1.43343608, 3.53322437, 6.6486199 ,
       4.5102408 , 1.83870001, 5.41969773, 1.60624322, 2.0364837 ])

In [33]:
y.reshape(-1)

array([2.98640238, 4.37188555, 1.43441169, 3.41334039, 6.64188876,
       4.62337772, 1.82264062, 5.377855  , 1.70205578, 1.97594418])